export type RepresentativeProfile = {
  id: string;
  userId: string;
  profilePhoto?: string;
  fullName: string;
  gender?: string;
  dateOfBirth?: string;
  age?: number | null;
  mobileNumber?: string;
  email?: string;
  city?: string;
  state?: string;
  country?: string;
  occupation?: string;
  companyOrganization?: string;
  languagesKnown?: string[];
  relationship?: string;
  relationshipOther?: string;
  managingProfileFor?: string;
  about?: string;
  allowPhoneCalls?: boolean;
  allowWhatsApp?: boolean;
  allowEmail?: boolean;
  governmentIdUrl?: string;
  relationshipProofUrl?: string;
  isVerified?: boolean;
};

export type VendorProfile = {
  id: string;
  userId: string;
  businessLogo?: string;
  businessBanner?: string;
  businessName: string;
  ownerName?: string;
  category: string;
  categoryOther?: string;
  businessDescription?: string;
  yearsOfExperience?: number;
  teamSize?: number;
  pricingRange?: string;
  serviceCities?: string[];
  serviceStates?: string[];
  businessAddress?: string;
  googleMapsLocation?: string;
  mobileNumber?: string;
  email?: string;
  website?: string;
  instagram?: string;
  facebook?: string;
  whatsapp?: string;
  portfolioPhotos?: string[];
  portfolioVideos?: string[];
  governmentIdUrl?: string;
  gstNumber?: string;
  businessRegistrationUrl?: string;
  awards?: string[];
  certificates?: string[];
  isVerified?: boolean;
};
